version: 2
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          context: build-global
jobs:
  build:
    docker:
      # This image holds our core dependencies for building/deploying
      # including the necessary private pypi repository token to upload it when merged to master.
      - image: $BUILD_CONTAINER_IMAGE
        auth:
          # reserved username for authenticating against a docker registry
          # https://cloud.google.com/container-registry/docs/advanced-authentication
          username: _json_key
          # Set this through CircleCI's environment variables. Copy from trigger_mail.
          password: $TRIGGERMAIL_GCR_AUTH
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Set Bluecore environment and tools
          # $BASH_ENV is a reserved environment variable by CircleCI of the location
          # of their bashrc file. This allow us to add to the whole run's available commands easily.
          command: |
            ~/devenv/bluecore activate >> $BASH_ENV
      - run:
          name: Deploy to GCS (cdn.bluecore.com)
          command: |
            pwd
            if [[ $CIRCLE_BRANCH == 'master' ]]; then
              ./auth_gcloud.sh
              gsutil -h "Cache-Control:public,max-age=3600" -m rsync -a public-read -d -r ./config/ gs://bluecore-openapi-docs/
            fi
